# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Neotoma Database Workbooks
email: goring@wisc.edu
description: > # this means to ignore newlines until "baseurl:"
  A resource for paleoecological-related workbooks.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://neotomadb.org"
twitter_username: neotomadb
github_username:  neotomadb

project_button: Github

cookie_accept_message: Thanks!

# Build settings
markdown: kramdown

collections:
  workbooks:
    output: true
